/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Score = IDL.Record({
  'highestLevel' : IDL.Int,
  'highScore' : IDL.Int,
});
export const Profile = IDL.Record({
  'username' : IDL.Text,
  'devilFruit' : IDL.Text,
});
export const PlayerData = IDL.Record({ 'score' : Score, 'profile' : Profile });
export const PlayerInput = IDL.Record({
  'username' : IDL.Text,
  'highestLevel' : IDL.Int,
  'highScore' : IDL.Int,
  'devilFruit' : IDL.Text,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerData)], ['query']),
  'getPlayerData' : IDL.Func([], [PlayerData], ['query']),
  'setPlayerData' : IDL.Func([PlayerInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Score = IDL.Record({ 'highestLevel' : IDL.Int, 'highScore' : IDL.Int });
  const Profile = IDL.Record({
    'username' : IDL.Text,
    'devilFruit' : IDL.Text,
  });
  const PlayerData = IDL.Record({ 'score' : Score, 'profile' : Profile });
  const PlayerInput = IDL.Record({
    'username' : IDL.Text,
    'highestLevel' : IDL.Int,
    'highScore' : IDL.Int,
    'devilFruit' : IDL.Text,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func([], [IDL.Vec(PlayerData)], ['query']),
    'getPlayerData' : IDL.Func([], [PlayerData], ['query']),
    'setPlayerData' : IDL.Func([PlayerInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };